backend:
  name: git-gateway

slug:
  encoding: "ascii"
  clean_accents: true

media_folder: "static/media"
public_folder: "/media"

locale: "pt"

collections:
  - label: "Configurações"
    name: "config"
    files:
      - label: "Geral"
        name: "globals"
        file: "static/data/entities/config/globals.json"
        fields:
          - {label: "Nome do site", name: site_name, widget: string}
          - label: "Idioma padrão"
            name: "default_lang"
            widget: "select"
            options:
              - { label: "Português", value: "pt" }
              - { label: "Inglês", value: "en" }
      - label: "Homepage"
        name: "homepage"
        file: "static/data/entities/config/homepage.json"
        fields:
          - {label: "Título", name: title, widget: string}
          - {label: "Descrição", name: desc, widget: text}
  - name: "project"
    label: "Projetos"
    folder: "static/data/entities/project"
    extension: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de publicação", name: "date", widget: "datetime"}
      - {label: "Localização", name: "location", widget: "map" }
      - {label: "Foto principal", name: "image", widget: "image"}
      - label: "Fotos"
        required: false
        name: "images"
        widget: "image"
        media_library:
          config:
            multiple: true
      - {label: "Fase", name: "phase", widget: "string", required: false}
      - {label: "Resumo", name: "lede", widget: "text", required: false}
      - {label: "Descrição", name: "body", widget: "markdown", required: false}
